package com.github.nawafeo.Lean.model;

public enum Routine {
    JOSH_CLARK_C25K, HAL_HIGDON_N10K, HAL_HIGDON_I15k,
    BODYWEIGHT_FITNESS_RR, BODYWEIGHT_FITNESS_BWPPL, ANTRANIK_PPL, BODYWEIGHT_FITNESS_BWPLUS,
    FITNESS_BBR, JIM_WENDLER_531, CODY_LEFEVER_GZCLP, JASON_BLAHA_ICF, METALLICADPA_PPL, LAYNE_NORTON_PHAT,
    JOE_DEFRANCO_WS4SB
}
